### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by aminya** [root-project/cling#337]
Why all of the operating systems have binaries but Windows doesn't?

50% of developers use Windows.
https://insights.stackoverflow.com/survey/2019#technology-_-platforms

83% of people use Windows.
[![](https://res.cloudinary.com/marcomontalbano/image/upload/v1587271094/video_to_markdown/images/youtube--eJuvKn5j_kE-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://www.youtube.com/watch?v=eJuvKn5j_kE "")

**Comment by h5rdly** [comment]
Not a Windows fan, but I'm working on cross-platform code, would actually be great if there were Windows binaries available for cling.

**Comment by ax3l** [comment]
https://github.com/conda-forge/cling-feedstock/

**Comment by Cvar1984** [comment]
im looking for aarch64 binaries

**Comment by ax3l** [comment]
On Linux or Windows?

**Comment by h5rdly** [comment]
@ax3l It's nice that it's available there,should conda be a prerequisite? Clang comes with binaries to all imaginable platforms.. Why wouldn't cling make an official release to help adoption?

**Comment by ax3l** [comment]
Why not, you could propose a PR that runs a nightly and tag-based [GitHub Action](https://help.github.com/en/actions) that builds cling and uploads the build artifact.
Here is an example how to do this:
```yml
name: wheels

on:
  push:
    tags:
  release:
    types:
      - created
  schedule:
    # nightly at 1 AM
    - cron: '0 1 * * *'

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]

    steps:
    - uses: actions/checkout@v2
      name: Build with CMake
      run: |
        cmake-foo here installing into <somePrefixPath>
        zip artifacts in <somePrefixPath>
    - uses: actions/upload-artifact@v1
      name: Upload Artifact
      with:
        name: build & install
        path: ./somePrefixPath
```
